// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gopdcrtqrtcddvvsqjti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvcGRjcnRxcnRjZGR2dnNxanRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDQyNzYsImV4cCI6MjA2NTU4MDI3Nn0.PoRspjxnzhRLLGv-0uYVn7ra1ErAezsgh5UuCJFOxy4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);